Repository Weed-AI/Weed-AI, pull requests merged in 2020-10, with the labels that each got.

#82 Implement and test weedcoco validation
  .github/workflows/pytest.yml
  .github/workflows/validate_json.yml
  setup.py
  weedcoco/cwfid_to_json/cwfid_imageinfo.json
  weedcoco/importers/cwfid.py
  weedcoco/importers/deepweeds.py
  weedcoco/schema/main.yaml
  weedcoco/tests/__init__.py
  weedcoco/tests/test_validation.py
  weedcoco/validation.py
Labels: import, specification

#101 Add converter from Pascal VOC to Weed COCO
  setup.py
  tests/importers/__init__.py
  weedcoco/importers/voc.py
  weedcoco/tests/importers/__init__.py
  weedcoco/tests/importers/test_voc.py
  weedcoco/tests/importers/voc_data/VOC/resizeC1_PLOT_20190728_175852.xml
  weedcoco/tests/importers/voc_data/VOC/resizeC1_PLOT_20190728_180135.xml
  weedcoco/tests/importers/voc_data/agcontext.yaml
  weedcoco/tests/importers/voc_data/category_name_map1.yaml
  weedcoco/tests/importers/voc_data/category_name_map2.yaml
  weedcoco/tests/importers/voc_data/collection1.json
  weedcoco/tests/importers/voc_data/collection2.yaml
  weedcoco/tests/importers/voc_data/images/resizeC1_PLOT_20190728_175852.jpg
  weedcoco/tests/importers/voc_data/images/resizeC1_PLOT_20190728_180135.jpg
  weedcoco/utils.py
Labels: import

#110 dejavu removal
  search/docker-compose.yml
Labels: Frontend

#116 Reorganise filters in frontend
  search/scripts/weedcoco-to-elastic-index-bulk.py
  search/src/App.js
Labels: Frontend

#124 Frontend: Hide filter checkboxes unless hovered
  search/src/App.css
  search/src/App.js
Labels: Frontend

#128 More detail on result cards
  search/README.md
  search/src/App.css
  search/src/App.js
Labels: Frontend
